/**
 * Round-Trip Integration Tests
 *
 * Validates that ICS files generated by the generator can be parsed back
 * correctly by the parser, ensuring data integrity and RFC 5545 compliance.
 *
 * Requirements: 5.5
 */

import { generateICS, ICSGeneratorOptions } from './icsGenerator.js';
import { parseICS } from './icsParser.js';

describe('ICS Round-Trip Integration', () => {
  // Helper function to create test options
  const createTestOptions = (overrides = {}): ICSGeneratorOptions => ({
    appointmentId: '550e8400-e29b-41d4-a716-446655440000',
    patientName: 'Ana Martínez',
    patientEmail: 'ana@example.com',
    professionalName: 'Dr. María González',
    scheduledAt: new Date('2024-03-15T11:30:00'),
    durationMinutes: 60,
    notes: null,
    isCancellation: false,
    ...overrides,
  });

  it('round-trip: basic appointment data', () => {
    const options = createTestOptions();
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    // Verify UID
    expect(parsed.uid).toBe(
      'appointment-550e8400-e29b-41d4-a716-446655440000@anamnesia.pro'
    );

    // Verify summary contains professional name
    expect(parsed.summary).toContain('Dr. María González');

    // Verify timestamps (comparing time values to handle timezone differences)
    expect(parsed.startTime.getTime()).toBe(options.scheduledAt.getTime());
    expect(parsed.durationMinutes).toBe(options.durationMinutes);

    // Verify organizer and attendee
    expect(parsed.organizerName).toBe(options.professionalName);
    expect(parsed.attendeeName).toBe(options.patientName);
    expect(parsed.attendeeEmail).toBe(options.patientEmail);

    // Verify status and method
    expect(parsed.status).toBe('CONFIRMED');
    expect(parsed.method).toBe('REQUEST');
  });

  it('round-trip: appointment with notes', () => {
    const options = createTestOptions({
      notes: 'Patient has allergies to penicillin. Requires special care.',
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.description).toBe(
      'Patient has allergies to penicillin. Requires special care.'
    );
  });

  it('round-trip: appointment with special characters in notes', () => {
    const options = createTestOptions({
      notes:
        'Important: Patient has allergies, see notes;\nFollow up required\\urgent',
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.description).toBe(
      'Important: Patient has allergies, see notes;\nFollow up required\\urgent'
    );
  });

  it('round-trip: appointment with special characters in names', () => {
    const options = createTestOptions({
      professionalName: 'Dr. Smith, PhD; MD',
      patientName: 'John, Jr.; Smith',
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.organizerName).toBe('Dr. Smith, PhD; MD');
    expect(parsed.attendeeName).toBe('John, Jr.; Smith');
  });

  it('round-trip: cancelled appointment', () => {
    const options = createTestOptions({
      isCancellation: true,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.status).toBe('CANCELLED');
    expect(parsed.method).toBe('CANCEL');
  });

  it('round-trip: 30 minute appointment', () => {
    const options = createTestOptions({
      durationMinutes: 30,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.durationMinutes).toBe(30);
  });

  it('round-trip: 90 minute appointment', () => {
    const options = createTestOptions({
      durationMinutes: 90,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.durationMinutes).toBe(90);
  });

  it('round-trip: appointment at different time', () => {
    const scheduledAt = new Date('2024-06-20T14:00:00');
    const options = createTestOptions({
      scheduledAt,
      durationMinutes: 45,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.startTime.getTime()).toBe(scheduledAt.getTime());
    expect(parsed.durationMinutes).toBe(45);
  });

  it('round-trip: appointment with very long notes', () => {
    const longNotes = 'A'.repeat(500);
    const options = createTestOptions({
      notes: longNotes,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.description).toBe(longNotes);
  });

  it('round-trip: appointment with Spanish characters', () => {
    const options = createTestOptions({
      professionalName: 'Dra. María José González',
      patientName: 'José Ramón Martínez',
      notes: 'Paciente tiene alergias. Requiere atención especial.',
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.organizerName).toBe('Dra. María José González');
    expect(parsed.attendeeName).toBe('José Ramón Martínez');
    expect(parsed.description).toBe(
      'Paciente tiene alergias. Requiere atención especial.'
    );
  });

  it('round-trip: appointment without notes', () => {
    const options = createTestOptions({
      notes: null,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.description).toBeUndefined();
  });

  it('round-trip: verifies timezone is preserved', () => {
    const options = createTestOptions();
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.timezone).toBe('America/Argentina/Buenos_Aires');
  });

  it('round-trip: verifies end time calculation', () => {
    const startTime = new Date('2024-03-15T11:30:00');
    const durationMinutes = 60;
    const expectedEndTime = new Date(
      startTime.getTime() + durationMinutes * 60 * 1000
    );

    const options = createTestOptions({
      scheduledAt: startTime,
      durationMinutes,
    });
    const ics = generateICS(options);
    const parsed = parseICS(ics);

    expect(parsed.endTime.getTime()).toBe(expectedEndTime.getTime());
  });
});
